//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DEPARTAMENTDB : DbContext
    {
        public DEPARTAMENTDB()
            : base("name=DEPARTAMENTDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<ADAUGARE004_Result> ADAUGARE004(string nUME_DEP)
        {
            var nUME_DEPParameter = nUME_DEP != null ?
                new ObjectParameter("NUME_DEP", nUME_DEP) :
                new ObjectParameter("NUME_DEP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ADAUGARE004_Result>("ADAUGARE004", nUME_DEPParameter);
        }
    
        public virtual ObjectResult<ADAUGAREDEPARTAMENT_Result> ADAUGAREDEPARTAMENT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ADAUGAREDEPARTAMENT_Result>("ADAUGAREDEPARTAMENT");
        }
    
        public virtual ObjectResult<SELECTAREPERSONAL_Result> SELECTAREPERSONAL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SELECTAREPERSONAL_Result>("SELECTAREPERSONAL");
        }
    }
}
