//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DEPARTAMENT : DbContext
    {
        public DEPARTAMENT()
            : base("name=DEPARTAMENT")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ANGAJATI> ANGAJATIs { get; set; }
        public virtual DbSet<DEPARTAMENT> DEPARTAMENTs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual ObjectResult<ADAUGARE001_Result> ADAUGARE001(string nUME_DEP)
        {
            var nUME_DEPParameter = nUME_DEP != null ?
                new ObjectParameter("NUME_DEP", nUME_DEP) :
                new ObjectParameter("NUME_DEP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ADAUGARE001_Result>("ADAUGARE001", nUME_DEPParameter);
        }
    
        public virtual ObjectResult<ADAUGARE002_Result> ADAUGARE002(string nUME_DEP)
        {
            var nUME_DEPParameter = nUME_DEP != null ?
                new ObjectParameter("NUME_DEP", nUME_DEP) :
                new ObjectParameter("NUME_DEP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ADAUGARE002_Result>("ADAUGARE002", nUME_DEPParameter);
        }
    
        public virtual ObjectResult<ADAUGARE003_Result> ADAUGARE003(string nUME_DEP)
        {
            var nUME_DEPParameter = nUME_DEP != null ?
                new ObjectParameter("NUME_DEP", nUME_DEP) :
                new ObjectParameter("NUME_DEP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ADAUGARE003_Result>("ADAUGARE003", nUME_DEPParameter);
        }
    
        public virtual ObjectResult<ADAUGARE004_Result> ADAUGARE004(string nUME_DEP)
        {
            var nUME_DEPParameter = nUME_DEP != null ?
                new ObjectParameter("NUME_DEP", nUME_DEP) :
                new ObjectParameter("NUME_DEP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ADAUGARE004_Result>("ADAUGARE004", nUME_DEPParameter);
        }
    
        public virtual ObjectResult<ADAUGAREDEPARTAMENT_Result> ADAUGAREDEPARTAMENT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ADAUGAREDEPARTAMENT_Result>("ADAUGAREDEPARTAMENT");
        }
    
        public virtual ObjectResult<ADDANGAJATI002_Result> ADDANGAJATI002(Nullable<int> iD_DEPARTAMENT, string nUME, string pRENUME, string pOST_OCUPAT, string gENDER)
        {
            var iD_DEPARTAMENTParameter = iD_DEPARTAMENT.HasValue ?
                new ObjectParameter("ID_DEPARTAMENT", iD_DEPARTAMENT) :
                new ObjectParameter("ID_DEPARTAMENT", typeof(int));
    
            var nUMEParameter = nUME != null ?
                new ObjectParameter("NUME", nUME) :
                new ObjectParameter("NUME", typeof(string));
    
            var pRENUMEParameter = pRENUME != null ?
                new ObjectParameter("PRENUME", pRENUME) :
                new ObjectParameter("PRENUME", typeof(string));
    
            var pOST_OCUPATParameter = pOST_OCUPAT != null ?
                new ObjectParameter("POST_OCUPAT", pOST_OCUPAT) :
                new ObjectParameter("POST_OCUPAT", typeof(string));
    
            var gENDERParameter = gENDER != null ?
                new ObjectParameter("GENDER", gENDER) :
                new ObjectParameter("GENDER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ADDANGAJATI002_Result>("ADDANGAJATI002", iD_DEPARTAMENTParameter, nUMEParameter, pRENUMEParameter, pOST_OCUPATParameter, gENDERParameter);
        }
    
        public virtual ObjectResult<SELECTAREPERSONAL_Result> SELECTAREPERSONAL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SELECTAREPERSONAL_Result>("SELECTAREPERSONAL");
        }
    }
}
