//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANGAJATI
    {
        public int ID_ANGAJAT { get; set; }
        public int ID_DEPARTAMENT { get; set; }
        public string NUME { get; set; }
        public string PRENUME { get; set; }
        public string POST_OCUPAT { get; set; }
        public string GENDER { get; set; }
    
        public virtual DEPARTAMENT DEPARTAMENT { get; set; }
    }
}
