//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTAMENT
    {
        public DEPARTAMENT()
        {
            this.ANGAJATIs = new HashSet<ANGAJATI>();
        }
    
        public int ID_DEP { get; set; }
        public string NUME_DEP { get; set; }
    
        public virtual ICollection<ANGAJATI> ANGAJATIs { get; set; }
    }
}
