//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class departament : DbContext
    {
        public departament()
            : base("name=departament")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ANGAJATI> ANGAJATIs { get; set; }
        public DbSet<DEPARTAMENT> DEPARTAMENTs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual ObjectResult<ADAUGARE001_Result> ADAUGARE001(string nUME_DEP)
        {
            var nUME_DEPParameter = nUME_DEP != null ?
                new ObjectParameter("NUME_DEP", nUME_DEP) :
                new ObjectParameter("NUME_DEP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ADAUGARE001_Result>("ADAUGARE001", nUME_DEPParameter);
        }
    
        public virtual ObjectResult<ADAUGARE002_Result> ADAUGARE002(string nUME_DEP)
        {
            var nUME_DEPParameter = nUME_DEP != null ?
                new ObjectParameter("NUME_DEP", nUME_DEP) :
                new ObjectParameter("NUME_DEP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ADAUGARE002_Result>("ADAUGARE002", nUME_DEPParameter);
        }
    
        public virtual ObjectResult<ADAUGARE003_Result> ADAUGARE003(string nUME_DEP)
        {
            var nUME_DEPParameter = nUME_DEP != null ?
                new ObjectParameter("NUME_DEP", nUME_DEP) :
                new ObjectParameter("NUME_DEP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ADAUGARE003_Result>("ADAUGARE003", nUME_DEPParameter);
        }
    
        public virtual ObjectResult<ADAUGARE004_Result> ADAUGARE004(string nUME_DEP)
        {
            var nUME_DEPParameter = nUME_DEP != null ?
                new ObjectParameter("NUME_DEP", nUME_DEP) :
                new ObjectParameter("NUME_DEP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ADAUGARE004_Result>("ADAUGARE004", nUME_DEPParameter);
        }
    
        public virtual ObjectResult<ADAUGAREDEPARTAMENT_Result> ADAUGAREDEPARTAMENT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ADAUGAREDEPARTAMENT_Result>("ADAUGAREDEPARTAMENT");
        }
    
        public virtual ObjectResult<ADDANGAJATI002_Result> ADDANGAJATI002(Nullable<int> iD_DEPARTAMENT, string nUME, string pRENUME, string pOST_OCUPAT, string gENDER)
        {
            var iD_DEPARTAMENTParameter = iD_DEPARTAMENT.HasValue ?
                new ObjectParameter("ID_DEPARTAMENT", iD_DEPARTAMENT) :
                new ObjectParameter("ID_DEPARTAMENT", typeof(int));
    
            var nUMEParameter = nUME != null ?
                new ObjectParameter("NUME", nUME) :
                new ObjectParameter("NUME", typeof(string));
    
            var pRENUMEParameter = pRENUME != null ?
                new ObjectParameter("PRENUME", pRENUME) :
                new ObjectParameter("PRENUME", typeof(string));
    
            var pOST_OCUPATParameter = pOST_OCUPAT != null ?
                new ObjectParameter("POST_OCUPAT", pOST_OCUPAT) :
                new ObjectParameter("POST_OCUPAT", typeof(string));
    
            var gENDERParameter = gENDER != null ?
                new ObjectParameter("GENDER", gENDER) :
                new ObjectParameter("GENDER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ADDANGAJATI002_Result>("ADDANGAJATI002", iD_DEPARTAMENTParameter, nUMEParameter, pRENUMEParameter, pOST_OCUPATParameter, gENDERParameter);
        }
    
        public virtual ObjectResult<SELANGBYGENDER001_Result> SELANGBYGENDER001(string gENDER)
        {
            var gENDERParameter = gENDER != null ?
                new ObjectParameter("GENDER", gENDER) :
                new ObjectParameter("GENDER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SELANGBYGENDER001_Result>("SELANGBYGENDER001", gENDERParameter);
        }
    
        public virtual ObjectResult<SELECTAREPERSONAL_Result> SELECTAREPERSONAL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SELECTAREPERSONAL_Result>("SELECTAREPERSONAL");
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
